### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by humarci** [sujaykundu777/devlopr-jekyll#14]
I followed your instructions, but it is not running.

My last command:

```
$jekyll serve
```

Answer:
```
Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.1.4). We suggest you to upgrade to the version that created the lockfile by running `gem 
install bundler:2.1.4`.
Traceback (most recent call last):
        12: from C:/Ruby27-x64/bin/jekyll:23:in `<main>'
        11: from C:/Ruby27-x64/bin/jekyll:23:in `load'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/exe/jekyll:11:in `<top (required)>'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
         8: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler.rb:149:in `setup'
         7: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:20:in `setup'
         6: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:101:in `block in definition_method'
         5: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/definition.rb:226:in `requested_specs'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/definition.rb:237:in `specs_for'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/definition.rb:170:in `specs'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/spec_set.rb:80:in `materialize'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/spec_set.rb:80:in `map!'
```
versions:
```
$ ruby - v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x64-mingw32]

$ bundler -v
Bundler version 2.1.4
```

**Comment by sujaykundu777** [comment]
Try updating your bundle 

`bundle update & bundle install`

And then run 
`bundle exec jekyll serve` or `jekyll serve`
