### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by TheProgramSrc** [sujaykundu777/devlopr-jekyll#15]
Im having this error:

```
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize': Could not find nokogiri-1.10.8-x64-mingw32 in any of the sources (Bundler::GemNotFound)
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
        from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'

```

**Comment by sujaykundu777** [comment]
Hi , Can you try to install the gem by doing `bundle update && bundle install`

**Comment by TheProgramSrc** [comment]
I tried and nothing

**Comment by sujaykundu777** [comment]
Can you share your ruby, bundler and jekyll version.

**Comment by TheProgramSrc** [comment]
Sure:

ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x64-mingw32]
Bundler version 2.1.4

**Comment by sujaykundu777** [comment]
Thanks, Can you try with ruby 2.5.5. I think some dependencies like
nokogiri in latest ruby version is not supported

**Comment by TheProgramSrc** [comment]
I'll try it

**Comment by TheProgramSrc** [comment]
It worked! Thanks
